### PR TITLE
[Fix #178] Add tap-to-toggle UI explanation on first opening of reader

### PR DESCRIPTION
**Pull request by aferditamuriqi**

### CODE REVIEW

**Comment by winniequinn** [comment]
@aferditamuriqi I forget where we left off on this. I believe tap-to-toggle is _not_ presently working, correct?

**Comment by aferditamuriqi** [comment]
@winniequinn this pull request was a left over on "develop" branch, which i had moved, when i got rid of develop branch.

**Comment by winniequinn** [comment]
@aferditamuriqi If we no longer need this then, please feel free to close it.

**Comment by aferditamuriqi** [comment]
@winniequinn i would have to look into it first, as i honestly don't know what it does and if it's needed.

**Pull request closed without merging**
