### PR TITLE
changed log entry to not post to bugsnag #265

### LINKED ISSUE #265: Handle FeedHTTPTransportException
04-25 13:39:23.414  16383-16383/org.nypl.labs.OpenEbooks.app E/org.nypl.simplified.app.catalog.CatalogFeedActivity﹕ Failed to get feed: org.nypl.simplified.books.core.FeedHTTPTransportException: 401: UNAUTHORIZED
    No problem report was provided.
            at org.nypl.simplified.books.core.FeedHTTPTransport$1.onHTTPError(FeedHTTPTransport.java:77) ~[na:0.0]
            at org.nypl.simplified.books.core.FeedHTTPTransport$1.onHTTPError(FeedHTTPTransport.java:72) ~[na:0.0]
            at org.nypl.simplified.http.core.HTTPResultError.matchResult(HTTPResultError.java:134) ~[na:0.0]
            at org.nypl.simplified.books.core.FeedHTTPTransport.getStream(FeedHTTPTransport.java:69) ~[na:0.0]
            at org.nypl.simplified.books.core.FeedHTTPTransport.getStream(FeedHTTPTransport.java:29) ~[na:0.0]
            at org.nypl.simplified.books.core.FeedLoader.loadFeedStreamRetryingAuth(FeedLoader.java:401) ~[na:0.0]
            at org.nypl.simplified.books.core.FeedLoader.loadFeed(FeedLoader.java:343) ~[na:0.0]
            at org.nypl.simplified.books.core.FeedLoader.access$200(FeedLoader.java:48) ~[na:0.0]
            at org.nypl.simplified.books.core.FeedLoader$2.call(FeedLoader.java:227) ~[na:0.0]
            at org.nypl.simplified.books.core.FeedLoader$2.call(FeedLoader.java:222) ~[na:0.0]
            at java.util.concurrent.FutureTask.run(FutureTask.java:237) ~[na:0.0]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) ~[na:0.0]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) ~[na:0.0]
            at org.nypl.simplified.app.Simplified$1$1.run(Simplified.java:227) ~[na:0.0]
            at java.lang.Thread.run(Thread.java:818) ~[na:0.0]

### PR DESCRIPTION
**Pull request by aferditamuriqi**
removed logging exception, did just add bugsnag entries which are not needed

fixes #265

### CODE REVIEW

**Comment by winniequinn** [comment]
@aferditamuriqi Given how noisy the rest of the app's logging is, it seems maybe not quite right to disable this logging entirely. Can we just log it at a non-error level so Bugsnag doesn't pick it up?

**Comment by aferditamuriqi** [comment]
@winniequinn you're right, could use maybe warning instead of error?

**Comment by winniequinn** [comment]
@aferditamuriqi I'd probably use `info` because it's not a problem with the app itself but either one is okay with me.

**Comment by aferditamuriqi** [comment]
@winniequinn made the change

**Comment by winniequinn** [comment]
@aferditamuriqi Looks good! 👍

**Pull request merged**
