### PR TITLE
Add alameda county library

### PR DESCRIPTION
**Pull request by datalogics-dans**
This adds Califa's Alameda County Library to the multi-library list
and adds their theme settings to the app.
Also added .DS_Store to ignore since I'm developing on a Mac.

EULA, etc. links still to come.

### CODE REVIEW

**Comment by datalogics-bhaugen** [comment]
@leonardr / @aferditamuriqi, please coordinate with us before merging this branch so that Alameda does not accidentally get released before we are completely ready to do so.

**Comment by aferditamuriqi** [comment]
@datalogics-bhaugen of course, we'll make sure to coordinate.

**Comment by datalogics-dans** [comment]
@aferditamuriqi In light of [this page](https://github.com/NYPL-Simplified/Simplified/wiki/UniqueLibraryIDs) that I just found out existed, I'm guessing I should go through and change all the IDs in this PR to 7, correct?

**Comment by aferditamuriqi** [comment]
@datalogics-dans yes that would be great.

**Comment by gioneill** [comment]
Branch assets have been merged in as part of 
https://github.com/NYPL-Simplified/android/pull/462

When the time comes to bring the library online, only the Accounts.json file will be updated separately.

**Pull request closed without merging**
