### PR TITLE
Remove redundant summary text from entries in app settings.

### PR DESCRIPTION
**Pull request by twaddington**
Small copy change to remove some extraneous information from the settings page.

This is just a suggestion that improves the readability a bit. For copy changes like this, do we need to go through an approval process?

- [Screenshot: Before](https://user-images.githubusercontent.com/107117/71929967-9af2c400-314f-11ea-93a1-1f4ad724bc14.png)
- [Screenshot: After](https://user-images.githubusercontent.com/107117/71929992-a5ad5900-314f-11ea-8c80-5c184c5fee97.png)

### CODE REVIEW

**Comment by io7m** [comment]
Hehe, you're moving quickly! See my comment on #667 about "...".

I guess getting rid of the descriptive text entirely is a way to keep consistency. :smile:

**Comment by io7m** [comment]
Best to ask @killerpuppytails (Risa) if there's anything you think might require approval. I think minor things like this generally don't - in fact this descriptive text didn't exist at all prior to the single-activity work.

**Comment by io7m** [comment]
I'm in favour of having less text to translate, in general.

**Comment by twaddington** [comment]
@io7m thanks for that feedback. Making some minor changes like this helps me learn what processes you have in place.

I think folks are generally well trained on what's tappable in apps at this point. I'm not aware of the ellipsis being an established pattern on Android. Unless you've seen specific instances of confusion here?

**Comment by killerpuppytails** [comment]
Thanks for the tag, Mark. Tristan, for these types of things I should be involved, since we have other apps (not just our two) with which we want to maintain consistency. That said if you're not adding text it's usually a "yeah that's good," there's not much process beyond it. This is great and gets a thumbs up from me.

**Comment by io7m** [comment]
> I think folks are generally well trained on what's tappable in apps at this point. I'm not aware of the ellipsis being an established pattern on Android. Unless you've seen specific instances of confusion here?

I haven't, no.

**Comment by io7m** [comment]
Do these PRs need to be merged in a specific order? Both should go in. The failed build here was just our slightly-flaky build publication script. The actual build succeeded, but uploading it to the binaries repos didn't.

**Comment by twaddington** [comment]
> Do these PRs need to be merged in a specific order? &mdash; @io7m 

Nope! They are separate and can be merged in any order.

> Thanks for the tag, Mark. Tristan, for these types of things I should be involved, since we have other apps (not just our two) with which we want to maintain consistency. That said if you're not adding text it's usually a "yeah that's good," there's not much process beyond it. This is great and gets a thumbs up from me. &mdash; @killerpuppytails 

Thanks for taking a look! I'll be sure to tag you on any similar changes. Nice to know you're active on GitHub!

**Pull request merged**
